# Generated by Django 4.2.30 on 2026-05-31 08:17

import apps.core.blocks
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('taggit', '0005_auto_20220424_2025'),
        ('wagtailcore', '0091_embed'),
        ('cities', '0002_alter_citypage_badge_alter_citypage_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary (small image)'), ('summary_large_image', 'Summary with Large Image (recommended)')], default='summary_large_image', max_length=30)),
                ('noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page')),
                ('category', models.CharField(choices=[('tourism', 'Tourism News'), ('openings', 'New Openings'), ('events', 'Events & Festivals'), ('transport', 'Transport & Infrastructure'), ('culture', 'Culture & Heritage'), ('practical', 'Practical Updates'), ('visa', 'Visa & Entry')], default='tourism', max_length=30)),
                ('author_name', models.CharField(default='TravelGuide Editorial', max_length=200)),
                ('author_twitter', models.CharField(blank=True, help_text='@handle without the @', max_length=50)),
                ('published_date', models.DateField(default=django.utils.timezone.now, help_text='Date shown publicly and used in Schema.org / OG meta')),
                ('updated_date', models.DateField(blank=True, help_text='Leave blank if article has not been updated since first publish', null=True)),
                ('excerpt', models.TextField(blank=True, help_text='Shown in card previews and used as meta description when no SEO description is set', max_length=300)),
                ('reading_time', models.PositiveSmallIntegerField(default=3, help_text='Minutes to read')),
                ('is_featured', models.BooleanField(default=False, help_text='Highlight at the top of the listing page')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('source_name', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('body', wagtail.fields.StreamField([('rich_text', apps.core.blocks.BodyRichTextBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('full', 'Full width'), ('center', 'Centered'), ('left', 'Float left'), ('right', 'Float right')]))])), ('gallery', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False))]), label='Photos')), ('columns', wagtail.blocks.ChoiceBlock(choices=[('2', '2 cols'), ('3', '3 cols'), ('4', '4 cols')]))])), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('attribution', wagtail.blocks.CharBlock(required=False)), ('attribution_role', wagtail.blocks.CharBlock(label='Role / source', required=False))])), ('alert', wagtail.blocks.StructBlock([('style', wagtail.blocks.ChoiceBlock(choices=[('info', 'ℹ️  Info'), ('tip', '💡  Tip'), ('warning', '⚠️  Warning'), ('success', '✅  Good to know')])), ('heading', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul']))])), ('cta', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Button text')), ('page', wagtail.blocks.PageChooserBlock(label='Internal page', required=False)), ('url', wagtail.blocks.URLBlock(label='External URL (overrides page)', required=False)), ('style', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primary — gold'), ('outline', 'Outline')]))])), ('cards', wagtail.blocks.StructBlock([('columns', wagtail.blocks.ChoiceBlock(choices=[('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')], label='Grid columns')), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], required=False)), ('cta', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Button text')), ('page', wagtail.blocks.PageChooserBlock(label='Internal page', required=False)), ('url', wagtail.blocks.URLBlock(label='External URL (overrides page)', required=False)), ('style', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primary — gold'), ('outline', 'Outline')]))], label='Button (optional)', required=False))])))])), ('accordion', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Section heading (optional)', required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Question / heading')), ('content', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul']))])))])), ('stats', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('stats', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.CharBlock(help_text='e.g. "+73%", "7,000", "4"')), ('label', wagtail.blocks.CharBlock())])))])), ('timeline', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('marker', wagtail.blocks.CharBlock(help_text='e.g. "Day 1" or "Apr 15"', label='Day / Date')), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('video', wagtail.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(help_text='Paste a YouTube or Vimeo URL')), ('caption', wagtail.blocks.CharBlock(required=False))])), ('document', wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('title', wagtail.blocks.CharBlock(help_text='Override document title (optional)', required=False)), ('description', wagtail.blocks.CharBlock(required=False))])), ('two_columns', wagtail.blocks.StructBlock([('ratio', wagtail.blocks.ChoiceBlock(choices=[('half', '50 / 50'), ('wider-left', '60 / 40'), ('wider-right', '40 / 60')], label='Column ratio')), ('left', wagtail.blocks.RichTextBlock(label='Left column')), ('right', wagtail.blocks.RichTextBlock(label='Right column'))])), ('html', apps.core.blocks.RawHTMLBlock())], use_json_field=True)),
                ('cover_image', models.ForeignKey(blank=True, help_text='Hero / card image. Also used as OG image when no separate og_image is set', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social share image — 1200×630 px (Facebook, LinkedIn, Telegram)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('primary_city', models.ForeignKey(blank=True, help_text='Main city this article is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='cities.citypage')),
                ('related_cities', modelcluster.fields.ParentalManyToManyField(blank=True, help_text='Additional cities mentioned in this article', related_name='related_news', to='cities.citypage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='NewsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='news.newsarticle')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='news.NewsTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
