# Generated by Django 4.2.30 on 2026-05-31 06:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0090_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='CityPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary (small image)'), ('summary_large_image', 'Summary with Large Image (recommended)')], default='summary_large_image', max_length=30)),
                ('noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page')),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('description', wagtail.fields.RichTextField()),
                ('featured_order', models.PositiveSmallIntegerField(default=99, help_text='Lower number = appears first on homepage')),
                ('is_featured', models.BooleanField(default=False)),
                ('badge', models.CharField(blank=True, help_text='Short badge text, e.g. "Must Visit" or "UNESCO"', max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('body', wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock(label='Rich Text')), ('highlight', wagtail.blocks.StructBlock([('icon', wagtail.blocks.CharBlock(required=False)), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock())], label='Highlight Block')), ('gallery', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False))]), label='Photo Gallery'))], blank=True, use_json_field=True)),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social share image — 1200×630 px (Facebook, LinkedIn, Telegram)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
