# Generated by Django 4.2.30 on 2026-05-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_citypage_hide_footer_citypage_hide_nav_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citypage',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Auto-filled by the location search above — or enter manually (e.g. 39.654000)', max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='citypage',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Auto-filled by the location search above — or enter manually (e.g. 66.975400)', max_digits=9, null=True),
        ),
    ]
