# Generated by Django 4.2.30 on 2026-06-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('leaderboard_code', models.TextField(blank=True, help_text='970×90 — homepage, above the fold.', verbose_name='Ad code')),
                ('midpage_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('midpage_code', models.TextField(blank=True, help_text='728×90 — homepage, mid-page banner.', verbose_name='Ad code')),
                ('article_inline_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('article_inline_code', models.TextField(blank=True, help_text='728×90 — inline within city pages, blog posts, and news articles.', verbose_name='Ad code')),
                ('sidebar_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('sidebar_code', models.TextField(blank=True, help_text='300×250 — homepage and article sidebars.', verbose_name='Ad code')),
                ('footer_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('footer_code', models.TextField(blank=True, help_text='Full-width — above the footer on every page.', verbose_name='Ad code')),
            ],
            options={
                'verbose_name': 'Ad Placements',
            },
        ),
        migrations.CreateModel(
            name='SectionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_cities', models.BooleanField(default=True, verbose_name='Cities')),
                ('show_sights', models.BooleanField(default=True, verbose_name='Sights')),
                ('show_eat', models.BooleanField(default=False, help_text='Off by default — turn on once restaurant content is ready to monetize.', verbose_name='Eat (Restaurants)')),
                ('show_stay', models.BooleanField(default=False, help_text='Off by default — turn on once hotel content is ready to monetize.', verbose_name='Stay (Hotels)')),
                ('show_routes', models.BooleanField(default=True, verbose_name='Routes')),
                ('show_visa', models.BooleanField(default=True, verbose_name='Visa & Entry')),
                ('show_practical', models.BooleanField(default=True, verbose_name='Practical')),
                ('show_news', models.BooleanField(default=True, verbose_name='News')),
                ('show_blog', models.BooleanField(default=True, verbose_name='Blog / Tips')),
            ],
            options={
                'verbose_name': 'Sections',
            },
        ),
    ]
