# Generated by Django 4.2.30 on 2026-06-21 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='UzbekTrip', max_length=120)),
                ('twitter_handle', models.CharField(blank=True, default='@uzbektrip', help_text='Include the @ — used as the twitter:site meta tag.', max_length=50)),
                ('same_as_links', models.TextField(blank=True, help_text="One URL per line (Facebook, Instagram, YouTube, etc.) — used as the Organization's sameAs schema.org property.", verbose_name='Social profile URLs')),
                ('default_og_image', models.ForeignKey(blank=True, help_text="Fallback social share image (1200×630px) for any page that doesn't set its own.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('organization_logo', models.ForeignKey(blank=True, help_text='Used as the Organization logo in schema.org markup. Falls back to the static site logo if left blank.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'SEO',
            },
        ),
    ]
