# Generated by Django 4.2.30 on 2026-06-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seosettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ga4_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('ga4_code', models.TextField(blank=True, help_text='Paste the full Google tag (gtag.js) snippet from Google Analytics, including <script> tags.', verbose_name='GA4 tracking code')),
                ('yandex_metrica_enabled', models.BooleanField(default=False, verbose_name='Enabled')),
                ('yandex_metrica_code', models.TextField(blank=True, help_text='Paste the full counter code from Yandex Metrica, including <script> tags.', verbose_name='Yandex Metrica tracking code')),
            ],
            options={
                'verbose_name': 'Analytics',
            },
        ),
    ]
