# Generated by Django 4.2.30 on 2026-06-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analyticssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionsettings',
            name='show_cities',
            field=models.BooleanField(default=True, verbose_name='Destinations'),
        ),
    ]
