# Generated by Django 4.2.30 on 2026-05-31 06:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0090_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutesIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='RoutePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary (small image)'), ('summary_large_image', 'Summary with Large Image (recommended)')], default='summary_large_image', max_length=30)),
                ('noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page')),
                ('duration', models.CharField(help_text='e.g. "5 Days" or "10 Days"', max_length=50)),
                ('cities_covered', models.CharField(blank=True, help_text='Comma-separated city names shown under the route card', max_length=300)),
                ('featured_order', models.PositiveSmallIntegerField(default=99)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging')], default='easy', max_length=20)),
                ('best_season', models.CharField(blank=True, help_text='e.g. April–May, Sep–Oct', max_length=100)),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('body', wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('day', wagtail.blocks.StructBlock([('day_number', wagtail.blocks.CharBlock(label='Day')), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))], label='Day Itinerary'))], blank=True, use_json_field=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social share image — 1200×630 px (Facebook, LinkedIn, Telegram)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
