# Generated by Django 4.2.30 on 2026-06-21 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routepage',
            name='cover_image',
            field=models.ForeignKey(blank=True, help_text='Upload at least 1200×1600px, portrait — used as a tall card image. Auto-cropped and served as WebP.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
    ]
