# Generated by Django 4.2.30 on 2026-05-31 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0090_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary (small image)'), ('summary_large_image', 'Summary with Large Image (recommended)')], default='summary_large_image', max_length=30)),
                ('noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page')),
                ('hero_eyebrow', models.CharField(default='The Silk Road Reborn', max_length=120)),
                ('hero_title', models.CharField(default='Discover Uzbekistan', max_length=200)),
                ('hero_subtitle', models.TextField(blank=True, default='7,000 years of civilization. Turquoise domes that pierce the desert sky. A hospitality that will rearrange your understanding of welcome.')),
                ('hero_cta_primary_text', models.CharField(default='Explore Cities', max_length=60)),
                ('hero_cta_secondary_text', models.CharField(default='Plan Your Route', max_length=60)),
                ('stat1_number', models.CharField(default='+73%', max_length=20)),
                ('stat1_label', models.CharField(default='Tourist growth vs 2019', max_length=80)),
                ('stat2_number', models.CharField(default='100', max_length=20)),
                ('stat2_label', models.CharField(default='Visa-free countries', max_length=80)),
                ('stat3_number', models.CharField(default='7,000', max_length=20)),
                ('stat3_label', models.CharField(default='Years of history', max_length=80)),
                ('stat4_number', models.CharField(default='4', max_length=20)),
                ('stat4_label', models.CharField(default='UNESCO World Heritage Sites', max_length=80)),
                ('visa_title', models.CharField(default='Visa-Free for 100+ Countries', max_length=200)),
                ('visa_body', models.TextField(blank=True, default='Uzbekistan has opened its doors to the world. Check if your country qualifies for visa-free entry, or learn how to apply for an e-Visa in minutes.')),
                ('hero_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social share image — 1200×630 px (Facebook, LinkedIn, Telegram)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
