# Generated by Django 4.2.30 on 2026-05-31 06:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('wagtailcore', '0090_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', wagtail.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('twitter_card_type', models.CharField(choices=[('summary', 'Summary (small image)'), ('summary_large_image', 'Summary with Large Image (recommended)')], default='summary_large_image', max_length=30)),
                ('noindex', models.BooleanField(default=False, help_text='Prevent search engines from indexing this page')),
                ('category', models.CharField(choices=[('food', 'Food & Drink'), ('practical', 'Practical Info'), ('sights', 'Sights & Attractions'), ('culture', 'Culture & History'), ('transport', 'Transport'), ('accommodation', 'Hotels & Guesthouses')], default='practical', max_length=30)),
                ('author_name', models.CharField(default='TravelGuide Editorial', max_length=200)),
                ('author_twitter', models.CharField(blank=True, max_length=50)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary shown in card previews (max 300 chars)', max_length=300)),
                ('reading_time', models.PositiveSmallIntegerField(default=5, help_text='Estimated minutes')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False)),
                ('body', wagtail.fields.StreamField([('rich_text', wagtail.blocks.RichTextBlock()), ('pull_quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.CharBlock()), ('attribution', wagtail.blocks.CharBlock(required=False))], label='Pull Quote')), ('image_block', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False)), ('full_width', wagtail.blocks.CharBlock(required=False))], label='Image'))], use_json_field=True)),
                ('cover_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('og_image', models.ForeignKey(blank=True, help_text='Social share image — 1200×630 px (Facebook, LinkedIn, Telegram)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='BlogPostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='blog.blogpost')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='taggit.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='blog.BlogPostTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
