# Generated by Django 4.2.30 on 2026-05-31 08:25

import apps.core.blocks
from django.db import migrations, models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogpost_body_alter_blogpost_excerpt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='hide_footer',
            field=models.BooleanField(default=False, help_text='Hide the site footer'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='hide_nav',
            field=models.BooleanField(default=False, help_text='Hide the top navigation bar (useful for landing pages)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.fields.StreamField([('rich_text', apps.core.blocks.BodyRichTextBlock()), ('image', wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False)), ('attribution', wagtail.blocks.CharBlock(required=False)), ('alignment', wagtail.blocks.ChoiceBlock(choices=[('full', 'Full width'), ('center', 'Centered'), ('left', 'Float left'), ('right', 'Float right')]))])), ('gallery', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('caption', wagtail.blocks.CharBlock(required=False))]), label='Photos')), ('columns', wagtail.blocks.ChoiceBlock(choices=[('2', '2 cols'), ('3', '3 cols'), ('4', '4 cols')]))])), ('quote', wagtail.blocks.StructBlock([('quote', wagtail.blocks.TextBlock()), ('attribution', wagtail.blocks.CharBlock(required=False)), ('attribution_role', wagtail.blocks.CharBlock(label='Role / source', required=False))])), ('alert', wagtail.blocks.StructBlock([('style', wagtail.blocks.ChoiceBlock(choices=[('info', 'ℹ️  Info'), ('tip', '💡  Tip'), ('warning', '⚠️  Warning'), ('success', '✅  Good to know')])), ('heading', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul']))])), ('cta', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Button text')), ('page', wagtail.blocks.PageChooserBlock(label='Internal page', required=False)), ('url', wagtail.blocks.URLBlock(label='External URL (overrides page)', required=False)), ('style', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primary — gold'), ('outline', 'Outline')]))])), ('cards', wagtail.blocks.StructBlock([('columns', wagtail.blocks.ChoiceBlock(choices=[('2', '2 columns'), ('3', '3 columns'), ('4', '4 columns')], label='Grid columns')), ('cards', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul'], required=False)), ('cta', wagtail.blocks.StructBlock([('text', wagtail.blocks.CharBlock(label='Button text')), ('page', wagtail.blocks.PageChooserBlock(label='Internal page', required=False)), ('url', wagtail.blocks.URLBlock(label='External URL (overrides page)', required=False)), ('style', wagtail.blocks.ChoiceBlock(choices=[('primary', 'Primary — gold'), ('outline', 'Outline')]))], label='Button (optional)', required=False))])))])), ('accordion', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(label='Section heading (optional)', required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(label='Question / heading')), ('content', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link', 'ol', 'ul']))])))])), ('stats', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('stats', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('number', wagtail.blocks.CharBlock(help_text='e.g. "+73%", "7,000", "4"')), ('label', wagtail.blocks.CharBlock())])))])), ('timeline', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('marker', wagtail.blocks.CharBlock(help_text='e.g. "Day 1" or "Apr 15"', label='Day / Date')), ('title', wagtail.blocks.CharBlock()), ('description', wagtail.blocks.RichTextBlock(features=['bold', 'italic', 'link'])), ('image', wagtail.images.blocks.ImageChooserBlock(required=False))])))])), ('video', wagtail.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(help_text='Paste a YouTube or Vimeo URL')), ('caption', wagtail.blocks.CharBlock(required=False))])), ('document', wagtail.blocks.StructBlock([('document', wagtail.documents.blocks.DocumentChooserBlock()), ('title', wagtail.blocks.CharBlock(help_text='Override document title (optional)', required=False)), ('description', wagtail.blocks.CharBlock(required=False))])), ('table', apps.core.blocks.TableBlock()), ('two_columns', wagtail.blocks.StructBlock([('ratio', wagtail.blocks.ChoiceBlock(choices=[('half', '50 / 50'), ('wider-left', '60 / 40'), ('wider-right', '40 / 60')], label='Column ratio')), ('left', wagtail.blocks.RichTextBlock(label='Left column')), ('right', wagtail.blocks.RichTextBlock(label='Right column'))])), ('html', apps.core.blocks.RawHTMLBlock())], use_json_field=True),
        ),
    ]
