# Generated by Django 4.2.30 on 2026-06-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visaindexpage',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='Comma-separated. Most search engines ignore this now, but some verticals/aggregators still read it.', max_length=255),
        ),
    ]
